# Adapted from d-morrison/rpt's .lintr.R, trimmed to what applies to a
# dependency-light subdirectory package.
#
# Two things this file gets wrong easily, both silent:
#   1. The result must be ASSIGNED to `linters`. A bare linters_with_defaults()
#      call is ignored, and lintr reports only "Found unused settings" rather
#      than failing -- so the config looks present and does nothing.
#   2. Any other top-level variable is reported as an unused setting, so the
#      helper below is built inline rather than assigned first.
linters <- lintr::linters_with_defaults(
  undesirable_function_linter = lintr::undesirable_function_linter(
    fun = lintr::modify_defaults(
      lintr::default_undesirable_functions,
      library = paste(
        "\nuse `::` or `usethis::use_import_from()`",
        "instead of modifying the global search path.",
        "\nSee <https://r-pkgs.org/code.html#sec-code-r-landscape>."
      )
    )
  ),
  # rex's shortcuts (boundary, or, anything, maybe) are bound into this
  # namespace by rex::register_shortcuts() in zzz.R, which runs at build time.
  # object_usage_linter analyses source without loading the package, so it
  # cannot see them and reports every shortcut as an undefined global.
  object_usage_linter = NULL
)

# tests/testthat.R is testthat's standard runner, generated by
# usethis::use_testthat(). Its two library() calls are the documented form and
# cannot use `::`, so the file is excluded rather than the linter weakened.
exclusions <- list("tests/testthat.R")
