# Runs the standard check suite for R package repositories
name: Check R package

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check:
    permissions:
      contents: read
      pull-requests: read
    uses: Morrison-Lab/gha/.github/workflows/check-r-package.yml@v2
    # with:
    #   check-formatting: true
    #   check-duplicate-roxygen: true
    #   check-one-function-per-file: true
    #   check-news: true
    #   check-version: true
    #   fail: true
