# Copy to .github/workflows/check-math-definitions.yml in your repo.
name: Check Math Definitions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    uses: Morrison-Lab/gha/.github/workflows/check-math-definitions.yml@v3
