"""Display which docs version a multiversion altdoc build is rendering.

`generate_version_dropdown.py` rewrites a Quarto navbar's "Versions" menu with
one entry per deployed docs version. These helpers decide which of those
entries the current build *is*, and rewrite the two places that say so:

  - the menu's own label, which otherwise reads a static "Versions"
  - a version badge on the navbar title, after pkgdown, which renders the
    package version next to the navbar brand and colors it red on a
    development build (`inst/BS5/templates/navbar.html` and `R/development.R`
    in https://github.com/r-lib/pkgdown)

They live in their own module rather than inline in the script so they can be
unit-tested offline: importing the script itself runs its whole top-level
flow, which needs a git checkout and a resolved docs base URL.

The YAML helpers edit `quarto_website.yml` line by line, matching the script
they serve. A YAML round-trip would drop the comments consumers keep in that
file (see the `# Note:` blocks in d-morrison/rpt's copy).
"""

import html
import re
from typing import NamedTuple

# `current_version` value naming the development build, as opposed to a
# release tag. Callers that know which target they are rendering pass this
# (or a tag) explicitly; otherwise `resolve_current_version` infers it.
DEV = "dev"

STABLE_SUFFIX = " (stable)"
DEV_SUFFIX = " (dev)"

# Marks the navbar entry this action generates. The pre-rewrite config
# anchors the block with a literal `- text: Versions`, which the rewrite
# itself replaces with the version label -- so without a stable marker, a
# second run over an already-rewritten file could not find the block.
GENERATED_MARKER = (
    "# Generated by generate-altdoc-version-dropdown (d-morrison/gha);"
    " edits here are overwritten on every docs build."
)

# Anchor in a config this action has not rewritten yet.
_VERSIONS_ANCHOR = re.compile(r'\s+- text: ["\']?Versions["\']?\s*$')

_BADGE_CLASS = "navbar-version"
# pkgdown's own choice of Bootstrap utility classes: `danger` (red) for a
# development version, `muted` otherwise (`R/development.R`, `version_label`).
_DEV_CLASSES = f"{_BADGE_CLASS} text-danger"
_RELEASE_CLASSES = f"{_BADGE_CLASS} text-muted"
_BADGE = re.compile(
    rf"\s*<small class='{_BADGE_CLASS}\b[^>]*>.*?</small>", re.DOTALL
)

_TRUE = {"true", "1", "yes", "on"}
_FALSE = {"false", "0", "no", "off"}


class CurrentVersion(NamedTuple):
    """The docs version a build renders.

    `text` is the bare version as displayed (a tag like "v1.2.3", or a
    development version like "0.1.0.9000"); `label` adds the parenthetical
    the dropdown entries use; `is_dev` drives the badge's color.
    """

    text: str
    label: str
    is_dev: bool


def parse_bool(name, value):
    """Interpret a composite action's string input as a boolean.

    Raises ValueError on anything unrecognized rather than treating it as
    false, so a typo in a caller's `with:` block fails the build instead of
    silently turning the feature off.
    """
    normalized = (value or "").strip().lower()
    if normalized in _TRUE:
        return True
    if normalized in _FALSE:
        return False
    raise ValueError(
        f"{name} must be a boolean ('true' or 'false'), got {value!r}"
    )


def resolve_current_version(local_version, release_tags, latest_tag, override=""):
    """Return the `CurrentVersion` this build renders.

    `override` is the caller's explicit answer -- a release tag, or `DEV`.
    When it is empty, infer from `local_version`, the Version field of the
    rendered checkout's own DESCRIPTION: a release build renders a tag
    worktree, whose DESCRIPTION matches that tag, while the default branch
    and PR branches carry a development version no tag matches.
    """
    selected = (override or "").strip() or _infer_selection(
        local_version, release_tags
    )

    if selected == DEV:
        return CurrentVersion(local_version, local_version + DEV_SUFFIX, True)
    if latest_tag and selected == latest_tag:
        return CurrentVersion(selected, selected + STABLE_SUFFIX, False)
    # An archived release, or a tag published too recently to appear in the
    # release list this build collected -- either way, label it as itself.
    return CurrentVersion(selected, selected, False)


def _infer_selection(local_version, release_tags):
    tag = f"v{local_version}" if local_version else ""
    return tag if tag in release_tags else DEV


def format_dropdown_title(template, label):
    """Render the navbar menu's own label from a caller-supplied template."""
    if "{version}" not in template:
        raise ValueError(
            f"dropdown title template must contain '{{version}}', got {template!r}"
        )
    return template.replace("{version}", label)


def version_badge_html(version):
    """Return the navbar-title badge markup for a `CurrentVersion`."""
    classes = _DEV_CLASSES if version.is_dev else _RELEASE_CLASSES
    tooltip = "Development version" if version.is_dev else "Released version"
    return (
        f"<small class='{classes}' title='{tooltip}'>"
        f"{html.escape(version.text)}</small>"
    )


def find_versions_entry(lines):
    """Locate the navbar Versions menu in a `quarto_website.yml`.

    Returns `(block_start, entry_index, indent)`, where `block_start` is the
    generated-marker line when one is present (so a rewrite replaces it
    rather than stacking a second copy) and `entry_index` is the `- text:`
    line itself. Returns None when the config has no Versions menu.
    """
    for i, line in enumerate(lines):
        if line.strip() == GENERATED_MARKER:
            entry = _next_content_line(lines, i + 1)
            if entry is not None:
                return i, entry, _indent_of(lines[entry])
        if _VERSIONS_ANCHOR.match(line):
            return i, i, _indent_of(line)
    return None


def set_navbar_title(lines, entry_index, badge_html):
    """Append `badge_html` to the navbar's own title.

    Sets `website.navbar.title` rather than `website.title`, so the badge
    reaches the navbar without leaking markup into the page `<title>`, the
    feed, or social-card metadata. Seeds it from any existing navbar title,
    else from the site title.

    Returns `(lines, title)` -- with `title` None, and `lines` unchanged,
    when the config has neither, which the caller reports rather than
    failing the build: the dropdown label still names the version.
    """
    navbar = _find_ancestor_key(lines, entry_index, "navbar")
    if navbar is None:
        return lines, None
    navbar_index, navbar_indent = navbar

    base = None
    title_index = _find_child_key(lines, navbar_index, navbar_indent, "title")
    if title_index is not None:
        if _is_disabled_title(lines[title_index]):
            return lines, None
        base = _scalar_value(lines[title_index])
    else:
        website = _find_ancestor_key(lines, navbar_index, "website")
        if website is not None:
            site_title_index = _find_child_key(lines, website[0], website[1], "title")
            if site_title_index is not None:
                base = _scalar_value(lines[site_title_index])
    if base is None:
        return lines, None

    title = f"{_strip_version_badge(base)} {badge_html}".strip()
    indent = " " * _child_indent(lines, navbar_index, navbar_indent)
    new_line = f"{indent}title: {yaml_quote(title)}\n"

    lines = list(lines)
    if title_index is not None:
        lines[title_index] = new_line
    else:
        lines.insert(navbar_index + 1, new_line)
    return lines, title


def _strip_version_badge(title):
    """Drop a badge an earlier run left, so re-runs do not stack badges."""
    return _BADGE.sub("", title).strip()


def _indent_of(line):
    return len(line) - len(line.lstrip())


def _next_content_line(lines, start):
    for i in range(start, len(lines)):
        if lines[i].strip():
            return i
    return None


def _find_ancestor_key(lines, child_index, key):
    """Find the `key:` block containing the line at `child_index`."""
    child_indent = _indent_of(lines[child_index])
    pattern = re.compile(rf"^(\s*){re.escape(key)}:\s*$")
    for i in range(child_index - 1, -1, -1):
        match = pattern.match(lines[i])
        if match and len(match.group(1)) < child_indent:
            return i, len(match.group(1))
    return None


def _find_child_key(lines, parent_index, parent_indent, key):
    """Find `key:` among the direct children of the block at `parent_index`."""
    child_indent = _child_indent(lines, parent_index, parent_indent)
    pattern = re.compile(rf"^\s*{re.escape(key)}:(\s|$)")
    for i in range(parent_index + 1, len(lines)):
        if not lines[i].strip():
            continue
        indent = _indent_of(lines[i])
        if indent <= parent_indent:
            return None
        if indent == child_indent and pattern.match(lines[i]):
            return i
    return None


def _child_indent(lines, parent_index, parent_indent):
    """Indent of the block's children, or a two-space default if it has none."""
    first = _next_content_line(lines, parent_index + 1)
    if first is not None:
        indent = _indent_of(lines[first])
        if indent > parent_indent:
            return indent
    return parent_indent + 2


def _is_disabled_title(line):
    """True when `title:` is the unquoted YAML boolean `false`.

    Quarto renders `website.navbar.title: false` as no title at all -- what
    a consumer uses when a logo stands in for the wordmark -- so there is no
    title to hang a badge on. `title: "false"` is a quoted string, a
    (if odd) genuine title, and must not be treated the same way.
    """
    raw = line.split(":", 1)[1].strip()
    raw = raw.split(" #", 1)[0].strip()
    return raw.lower() == "false"


def _scalar_value(line):
    """Read the value of a `key: value` line, unquoting and decommenting it."""
    value = line.split(":", 1)[1].strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        inner = value[1:-1]
        if value[0] == '"':
            return inner.replace('\\"', '"').replace("\\\\", "\\")
        return inner.replace("''", "'")
    # Unquoted: everything from an inline `#` on is a YAML comment.
    return value.split(" #", 1)[0].strip()


def yaml_quote(value):
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
